
package market;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Market", targetNamespace = "http://Market/", wsdlLocation = "http://localhost:8082/Marketplace_Service/Market?WSDL")
public class Market_Service
    extends Service
{

    private final static URL MARKET_WSDL_LOCATION;
    private final static WebServiceException MARKET_EXCEPTION;
    private final static QName MARKET_QNAME = new QName("http://Market/", "Market");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/Marketplace_Service/Market?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKET_WSDL_LOCATION = url;
        MARKET_EXCEPTION = e;
    }

    public Market_Service() {
        super(__getWsdlLocation(), MARKET_QNAME);
    }

    public Market_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKET_QNAME, features);
    }

    public Market_Service(URL wsdlLocation) {
        super(wsdlLocation, MARKET_QNAME);
    }

    public Market_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKET_QNAME, features);
    }

    public Market_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Market_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Market
     */
    @WebEndpoint(name = "MarketPort")
    public Market getMarketPort() {
        return super.getPort(new QName("http://Market/", "MarketPort"), Market.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Market
     */
    @WebEndpoint(name = "MarketPort")
    public Market getMarketPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Market/", "MarketPort"), Market.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKET_EXCEPTION!= null) {
            throw MARKET_EXCEPTION;
        }
        return MARKET_WSDL_LOCATION;
    }

}
